### ISSUE TITLE
Detecting page/folder changes?

### ISSUE THREAD

**Issue by bicubic** [abcminiuser/python-elgato-streamdeck#101]
I might be missing something with this API, but there seems to be no way to make it play nice with the official Stream Deck software. I can read the state of a key and set an image, but once the Page or Folder feature is used, it overwrites the image and there seem to be no hooks to detect when this happens, and what page/folder has been selected?

If I have e.g. multiple pages and want to give away one of them to my Python script while the rest are managed by the supplied software, how would I do that?

**Comment by abcminiuser** [comment]
Hi @bicubic - unfortunately the StreamDeck itself has no concept of pages/folders - it's just a set of buttons and a display. There's no way for my library to know what the official software is doing with it any any point it time, so the two can't run together in any meaningful way.

That said, you can do what I do with the official software; I bind one of the buttons to a python script of my own, running through `pythonw.exe` on Windows so that it doesn't show an interpreter window. When I press the corresponding button on my StreamDeck my script runs in the background to control my lights.
