### ISSUE TITLE
Problem of io.BytesIO stream not closed in function _to_native_format in PILHelper

### ISSUE THREAD

**Issue by iPhoneAddict** [abcminiuser/python-elgato-streamdeck#152]
**Error**
When using the demo programs for Stream Deck tiled or animated images, it works but at the closure i have a bunch of Buffer Errors
> BufferError: Existing exports of data: object cannot be re-sized
> Exception ignored in: <_io.BytesIO object at 0x10342fce0>
> BufferError: Existing exports of data: object cannot be re-sized
> Exception ignored in: <_io.BytesIO object at 0x10342fd30>

**Reproduce**
I have that issue on any run of both demo Python scripts when i exit by hitting a key.

**StreamDeck Information**
Stream Deck XL

**System Information**
Mac Studio under O/S Ventura 13.7.1
Pillow stable 11.0.0
elgato-Streamdeck latest stable version

**Solution**
I am not good at Python so i asked ChatGPT to help me.
The solution solved my issue by modifying the end of _to_native_format
Previous code is in comment for reference
```
 # We want a compressed image in a given codec, convert.
#    compressed_image = io.BytesIO()
#    image.save(compressed_image, image_format['format'], quality=100)
#    return compressed_image.getbuffer()
    with io.BytesIO() as compressed_image:
        image.save(compressed_image, image_format['format'], quality=100)
        return compressed_image.getvalue()  # Return a secured copy of the data
```

**Comment by abcminiuser** [comment]
Thanks for the report, and I belive the suggestion is correct. The `getbuffer()` function returns a view into the existing data, but isn't intended to act as a lifetime extension for it (hence the warning). Returning a copy of the data once the encoding has completed should be the correct solution.

Fixed in https://github.com/abcminiuser/python-elgato-streamdeck/commit/09f0ab0dadec32651ebdc0aeeedd10ecb23ef78b.
