### ISSUE TITLE
Image quality could easily be better for (at least) original V2

### ISSUE THREAD

**Issue by ochilan** [abcminiuser/python-elgato-streamdeck#35]
Hello,

first off, thank you very much for this library – very easy to use, yet powerful.

I noticed, however, that the image quality on my StreamDeck original V2 is quite poor. This is especially noticable when having intense colors, e.g. red text on black background.

I quickly found that the image format for this device is defined to be JPEG in the code, and the poor quality I'm seeing are in fact compression artifacts. Specifying "quality = 100" as additional parameter to image.save() already improves the quality. However, I also noticed that the device seems to accept BMP just fine (although the image needs to be flipped vertically). The image quality is perfect then.

Is there a particular reason to use JPEG on this device?

**Comment by abcminiuser** [comment]
Interesting. The original StreamDeck (V1) can also do JPEG in addition to the regular BMP, but it's much slower to render and chokes on anything but very basic encodings.

Since I haven't got a ton of spare cash around to buy up all the StreamDeck variants I've been relying on the information I've found online to reverse engineer them - and they're all using JPEG for the StreamDeck XL, which is the precursor to the StreamDeck Original V2.

It's easy to change just the Original V2 to use BMP if you can confirm it doesn't make it significantly slower, and can help me out with tweaking the orientation flags to get it looking right. If someone else then confirms the XL works with BMP, we can switch that over too at a later date.

I've applied the `quality=100` change in ec9180c6d85db255bd0fe5aec09588996d5cee61 in the meantime, to reduce the artifacts.

**Comment by ochilan** [comment]
After some more testing, it seems like using BMP is indeed quite a bit slower than JPEG. I guess changing the JPEG quality to maximum is a good compromise then. Thank you!

**Comment by abcminiuser** [comment]
Closing for now as the change has been pushed - thanks for the help!
