### ISSUE TITLE
Stream Deck XL Performance

### ISSUE THREAD

**Issue by dubstech** [abcminiuser/python-elgato-streamdeck#36]
I wanted to see if anybody else is seeing a performance issue with the XL.  I have the XL connected to a raspberry pi 3, and it is working fine.  There are no errors I can see being thrown.  I have 3 "page" buttons that will toggle between pages of keys, so when a page button is pressed I highlight that button (load a new image) and then refresh about 20 of the keys to reflect the items in that page.  Most of the time the refresh happens very quickly with no problems, but every so many times a page button is pressed the XL seems to "freeze" for a moment and then will eventually load the new buttons without a problem.

It would make sense if the page switches were fast or slow every time, but the inconsistency is what is driving me crazy.  I have tried to do something to optimize the process by rendering all the buttons and storing them in memory and then just calling the set_key_image and passing it the rendered image.  I have also done things like only update buttons that are different.  It may have helped a little bit on the page flips, but didn't solve the "freezing" problem.  I can even hit the page buttons in rapid sequence and it will work many times and then all of the sudden freeze.  I can also switch the pages slowly and same problem.  I can't seem to find the root of the freeze and why it seems to happen randomly.

Any ideas on the best way to troubleshoot the root cause?

**Comment by abcminiuser** [comment]
I did notice my own Pi2 was a bit slow on HID requests, but that seemed to be linked to the underlying HID driver/kernel implementation rather than the library. I suspect it's something odd in the way the HID backend tries to access HID devices, which is causing the (in my case) approximately 100ms latency on my StreamDeck Original.

Which HID backend are you using? You should probably try using the `hid` backend rather than `hidapi`, with the latest `hidapi-libusb` OS library installed to ensure you're using the latest HID versions of the HID access APIs.

**Comment by abcminiuser** [comment]
Worth retrying on 0.7.0 now that the library dependencies have been removed and I'm binding to the system `libusb-hidapi0` package directly via ctypes - hopefully that'll reduce the number of system-specific variables that could be causing issues.
