### ISSUE TITLE
Random crashes with nothing in logs

### ISSUE THREAD

**Issue by 132ikl** [abcminiuser/python-elgato-streamdeck#39]
OS: Win 10
Using HID API

When set key images onto StreamDeck buttons, the script will crash randomly. There is no pattern to this. With logger on debug on, no crash relevant output is displayed. No exceptions are raised (this can by seen by surrounding set_key_image call in try/except) and the entire script instantly exits.

**Comment by abcminiuser** [comment]
Are you using the `hid` package along with the [latest released DLL](https://github.com/libusb/hidapi/releases) from the LibUSB project, or are you using the `hidapi` package?

**Comment by 132ikl** [comment]
I will double check, however I believe that I am using the `hid` pip package and I did install the linked DLLs.

**Comment by 132ikl** [comment]
I have confirmed this bug is reproducible on two Windows machines, using both `hid` and `hidapi` (wherein both cases the unused library was not installed)

**Comment by abcminiuser** [comment]
Can you please try [this work in progress branch](https://github.com/abcminiuser/python-elgato-streamdeck/tree/new_hid_transport) and report back? I'd expect it to work as well or as badly as the existing one, but it's the first step towards being able to debug it.

**Comment by 132ikl** [comment]
Unfortunately I won't have access to a StreamDeck until after the quarantine, but when I do I'll test it out and let you know.

**Comment by Subsentient** [comment]
I've suffered with this too, it results in memory corruption on Windows. My employer had tasked me with building a StreamDeck interface, and this library worked great -- on Linux. On Windows, memory corruption resulted in distorted images and eventually a segfault.

**Comment by abcminiuser** [comment]
Which version of the library are you testing, @subsentient?

**Comment by Subsentient** [comment]
> Which version of the library are you testing, @Subsentient?

This has been a problem in versions of this library all the way back in June. I had switched DLLs, Python DLL interface layers, rewrote my app to use Wand instead of Pillow (this was before the hard dependency), and eventually arrived at the conclusion that it was a flaw in HIDAPI, or in the way both Python interfaces to HIDAPI were talking to it.

**Comment by abcminiuser** [comment]
Yes, it is. I've replaced all the python wrappers and precompiled versions in the latest version of the library which is why I'm asking - in theory if there are still issues it's almost certainly a HIDAPI bug rather than bugs in one of the other (removed) parts of the stack.

**Comment by Subsentient** [comment]
> Yes, it is. I've replaced all the python wrappers and precompiled versions in the latest version of the library which is why I'm asking - in theory if there are still issues it's almost certainly a HIDAPI bug rather than bugs in one of the other (removed) parts of the stack.

What doesn't help me is that x64 gdb on Windows currently has a bug where it shows stack corruption even if there is none, making it much harder to debug accurately, paired with the lack of a Valgrind for Windows. Obviously valgrind+wine won't work for something that requires WinNT device drivers.

**Comment by Subsentient** [comment]
@abcminiuser Do you know if suffering through raw libusb would be portable, or do you think I should explore a native Windows backend using Microsoft APIs for this library?

**Comment by Subsentient** [comment]
@abcminiuser I've tested your latest changes on Windows, still gets a segmentation fault. Thought you'd want to know. Definitely an issue with hidapi on Windows.

**Comment by abcminiuser** [comment]
Ok, excellent, that's the information I wanted.

So that means we're down to pretty much down to either an error in my Python bindings, or an error in hidapi. I'm fairly certain its in the latter, as the wrapper code is pretty simple.

There's no API call in hidapi to get its release version, so it's possible there's multiple versions in your system's DLL search paths. Can you please ensure you're loading the latest released DLL?

HIDAPI for Windows is using APIs that are very similar to some Win32 HID code I wrote for my day job -- it looks fairly OK at first glace, but it probably needs a bit of a thorough review.

Are you using the latest Windows 10 public builds? Does it crash for you immediately, or after a while? With which StreamDeck? I use latest Windows 10, with the latest hidapi release DLL and an original StreamDeck, and haven't seen crashes thusfar.

Using libusb directly is a no go, as I've tried it before. The kernel HID driver binds to HID devices and won't let libusb use them without a lot of hackery.

**Comment by 132ikl** [comment]
I was using the latest Windows 10 release at the time, latest hidapi DLL, and the original StreamDeck as well. I'm pretty sure I didn't have multiple versions since I only ever installed the latest, but there's no way for me to confirm that. I still don't have access to the StreamDeck unfortunately so I can't give any updated info.

**Comment by 132ikl** [comment]
Also, as a note for me it only crashed after drawing many icons to the StreamDeck. There were no issues if I commented out `set_key_image` calls. More specifically, I called `set_key_image` once for each key on startup, and then once again every time the button was pressed. I never had any issues with the calls on startup, but the change on press is what was problematic.

**Comment by Subsentient** [comment]
@132ikl @abcminiuser Please compile and test my fork of HIDAPI for Windows.
There are many changes, and I can't get this version to crash. It still does the occasional corrupted picture write to buttons, though, but that happened in the old one too. I'm going to look into that more later today.

Build with MinGW/MSYS2 etc. This is C++ using RAII to prevent memory errors.

https://github.com/Subsentient/winhidapi

**Comment by Subsentient** [comment]
My latest commit in winhidapi seems to have fixed the image distortion too. Try it out, let me know! :^)

**Comment by 132ikl** [comment]
I will test it out when possible but unfortunately I don't have a StreamDeck to test it with and probably won't until late June/July/whenever stay at home orders are generally lifted.

**Comment by Subsentient** [comment]
@abcminiuser It turns out that the Windows driver APIs that handle HID devices are NOT thread safe, despite ReadFile and WriteFile generally being thread safe. I've patched it in winhidapi. You could stick a mutex around your read and write calls in your HID interface class if you like, though winhidapi does that for you now.

**Comment by abcminiuser** [comment]
Woah, that's...unexpected. Is it multiple concurrent reads/writes that cause corruption, or having both in flight at the same time? I can kind of see why multiple writes or multiple reads from different threads might cause issues, but if having a read on one thread while a write is issued on another it's going to be a pain to fix.

I took a look at your modifications - looks like having a blocking read on one thread will deadlock a write on another until a HID report comes in.

**Comment by Subsentient** [comment]
@abcminiuser Yeah, it will. But that's okay. In reality that should have been happening anyways, USB 2 doesn't support full duplex communications.

**Comment by hunter-hunter** [comment]
Sorry, should have included that in the original comment. I'm using 0.8.1

**Comment by 132ikl** [comment]
This is should probably be a separate issue, the previous issue was confirmed by 2 people to only affect non-Linux (although maybe arm handles it differently?)
