### ISSUE TITLE
Issue with devicemanager

### ISSUE THREAD

**Issue by sanderkik** [abcminiuser/python-elgato-streamdeck#49]
Hi, 

I tried to use the examples but I get an error (see below). I checked the installation of both streamdeckapi and the libusb.
Can anyone give some advise?

Traceback (most recent call last):
  File "C:\Users\Techniek\OneDrive - PKN Gouda\test\src\example_basic.py", line 110, in <module>
    streamdecks = DeviceManager().enumerate()
  File "C:\Users\Techniek\OneDrive - PKN Gouda\test\src\StreamDeck\DeviceManager.py", line 88, in __init__
    self.transport = self._get_transport(transport)
  File "C:\Users\Techniek\OneDrive - PKN Gouda\test\src\StreamDeck\DeviceManager.py", line 80, in _get_transport
    raise ProbeError("Probe failed to find any functional HID backend.", probe_errors)
StreamDeck.DeviceManager.ProbeError: ('Probe failed to find any functional HID backend.', {'libusb': TransportError("No suitable LibUSB HIDAPI library found on this system. Is the 'hidapi.dll' library installed?")})

**Comment by sanderkik** [comment]
resolved

**Comment by RogueNAND** [comment]
I was pulling my hair out for a while with this same error.
In case anyone else runs across this and is having a hard time understanding the libusb installation instructions:

Download the latest hidapi.dll file from [here](https://github.com/libusb/hidapi/releases).
I had to place the x86/hidapi.dll file into the Windows/SysWOW64 folder (yes, the 32 bit dll goes into the 64 bit windows folder. Not sure if this is intentional, but it worked for me).
_Note: I am running 32 bit version of python 3.8. Windows 10. YMMV_
