### ISSUE TITLE
In which profile is the key?

### ISSUE THREAD

**Issue by fooleranto** [abcminiuser/python-elgato-streamdeck#71]
Hello!

First of all, thank you very much for this great tool. I would like to design my layout with the Stream Deck software, including various sub-profiles. Then I would like to have a script that connects to the Stream Deck hardware (XL) and then just waits for a button to be pressed. And when a key is pressed, I would like to send a command to X-Plane based on this pressed key, possibly request a status (dataref) and make this status visible on the stream deck.

My problem is that your software, when I query the key (using state), I only ever get the key number 0-31, regardless of which profile on the stream deck I am currently in. Now the questions:

Is there any way to determine which profile is currently loaded?
Is there any way to find out which hotkey is assigned to a key?
Or is there a way to determine which type of key a key is (i.e. hotkey, or text, etc.)? If the key has been assigned the type "text", could this be read out?

Many greetings from Germany

Gunter

**Comment by abcminiuser** [comment]
Hi Gunter,

This library has no concept of "profiles" - it's just a way to draw your own custom buttons and get the button presses. It's up to the end application to implement whatever sort of profiles/nesting paging system you desired (like [this one](https://github.com/timothycrosley/streamdeck-ui/issuesl)).

If you're trying to get the profile from the official streamdeck client and respond to presses, this isn't the way to do it -- you should set the official client's button action to a custom python script of your choosing, so that the official app will call it when pressed.

Cheers!
- Dean
